### ISSUE TITLE
PNG file streams?

### ISSUE THREAD

**Issue by sustained** [twolfson/gif-encoder#11]
Can I use this library with [png-file-stream](https://github.com/eugeneware/png-file-stream) which is intended for use with **gifencoder** (not **gif-encoder**)?

Seems that **gifencoder** has broken transparency, so I can't use that.

**Comment by twolfson** [comment]
I don't believe it's possible to elegantly use `png-file-stream` and `gif-encoder` (this repo, not `gifencoder`) together. The main reason is we don't currently support `.pipe`/`.write`/`.end` methods -- we instead have our own methods (e.g. `writeHeader`, `addFrame`).

The same patch that fixed our broken transparency (i.e. #5 and #7) should work on `gifencoder` as well since we're based on the same port. In fact, we've noted this on https://github.com/eugeneware/gifencoder/pull/5#issuecomment-255684767

If you're interested in adding `.pipe` support to this library (i.e. updating it from `Readable` to `Duplex`), then I should be open to it -- main issue is making sure header is written on first write and knowing how to break on frames (prob require single `write` to be an entire frame which is what `png-file-stream` does).

If you're interested in a workaround for now, then the following should get you going:

```js
// Load in our dependencies
var pngFileStream = require('png-file-stream');
var GifEncoder = require('gif-encoder');

// Define a GIF and file to output to
var gif = new GifEncoder(10, 10);
var file = require('fs').createWriteStream('img.gif');
gif.pipe(file);

// Pipe our PNG data to our GIF as frames
gif.writeHeader();
pngFileStream('test/**/frame?.png').on('data', function handlePngData (pixelsBuff) {
  gif.addFrame(pixelsBuff)
}).on('finish', function handlePngFinish () {
  gif.finish();
});
```

**Comment by sustained** [comment]
Thanks a ton for the workaround!

Not sure if I am comfortable enough with *this kind of code* to be any use/help making it work with `Duplex` however I'll think about it as I'm trying to get into contributing to open-source anyway.

**Comment by twolfson** [comment]
I'm happy to help you along iterating on a PR. I personally don't have the time/prioritization to take it on myself
